name: Build

on:
  create: { }
  pull_request: { }

permissions:
  contents: write

jobs:
  x86:
    name: x86
    runs-on: ubuntu-24.04
    steps:
      - name: Download packages
        run: |
          sudo apt update
          sudo apt install -y mtools syslinux isolinux liblzma-dev genisoimage

      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: git tag (workaround)
        run: git tag -f v0.0.1

      - name: Build (BIOS)
        run: |
          make NO_WERROR=1 -j $(nproc) -C src

      - name: Release build artifacts
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./src/bin/ipxe.dsk
            ./src/bin/ipxe.lkrn
            ./src/bin/ipxe.pxe
            ./src/bin/undionly.kpxe
            ./src/bin/rtl8139.rom
            ./src/bin/8086100e.mrom
            ./src/bin/80861209.rom
            ./src/bin/10500940.rom
            ./src/bin/10222000.rom
            ./src/bin/10ec8139.rom
            ./src/bin/1af41000.rom
            ./src/bin/8086100f.mrom
            ./src/bin/808610d3.mrom
            ./src/bin/15ad07b0.rom
            ./src/bin/ipxe.usb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}